config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  get 'about', to: 'pages#about'
  get 'courses/new', to: 'courses#new'
  resources :students, except: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true, length: {minimum: 5, maximum: 50}
  validates :short_name, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 500}


end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX  }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def new 
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def new
    @students = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:success] = "You have successfully signed up"
      redirect_to root_path
    else
      render 'new'
    end
  end



  private
  def student_params
    params.require(:student).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/index.html.erb
<h1>Course listing</h1>

<div class="d-grid gap-3">
<% @courses.each do |course| %>
    <div class="card">
        <div class="card-body">
          <h3 class="card-title"><%= course.short_name %>: <%= course.name %></h3>
          <p class="card-text"><%= course.description %></p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
  <% end %>
  </div>

app/views/courses/new.html.erb
<h1>new page</h1>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnivApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <%= render 'layouts/navigation' %>

    <%= link_to 'home', root_path %>
    <%= link_to 'about', about_path %>
    <%= link_to 'new course', courses_new_path %>

  <div class="container">
    <%= yield %>
  </div>  

  </body>
</html>

app/views/pages/about.html.erb
<h1>about page</h1>

app/views/students/index.html.erb
<h1>Students listing</h1>

<div class="d-grid gap-3">
<% @students.each do |student| %>
    <div class="card">
        <div class="card-body">
          <h5 class="card-title">Name: <%= student.name %></h5>
          <p class="card-title">Email: <%= student.email %></p>
          <p>Course Enrollments: None</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
  <% end %>
  </div>

app/views/students/new.html.erb
<div class="container">

  <h1>Sign up</h1>

  <%= form_with model: @student do |f| %>
    <div class="mb-3 col-6">
      <%= f.label :name, calss: "form-label"%>
      <%= f.text_field :name, placeholder: "Enter your full name",autofocus: true, class: "form-control" %>
    </div>

    <div class="mb-3 col-6">
      <%= f.label :email, calss: "form-label"%>
      <%= f.text_field :email, placeholder: "Enter your email", class: "form-control" %>
    </div>

    <%= f.submit 'Sign up', data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-primary" %>
  <% end %>
</div>